// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"awesomeProject/dou-yin/apps/user/cmd/rpc/internal/logic"
	"awesomeProject/dou-yin/apps/user/cmd/rpc/internal/svc"
	"awesomeProject/dou-yin/apps/user/cmd/rpc/types/user"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Login(ctx context.Context, in *user.DouyinUserLoginRequest) (*user.DouyinUserLoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcServer) Register(ctx context.Context, in *user.DouyinUserRegisterRequest) (*user.DouyinUserRegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *RpcServer) UserInfo(ctx context.Context, in *user.DouyinUserRequest) (*user.DouyinUserResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
