// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	CommActionInterface "awesomeProject/dou-yin/commaction/api/internal/handler/CommActionInterface"
	"awesomeProject/dou-yin/commaction/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/favorite/action",
				Handler: CommActionInterface.FavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/favorite/list",
				Handler: CommActionInterface.FavoriteListRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/comment/action",
				Handler: CommActionInterface.CommmentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/comment/list",
				Handler: CommActionInterface.CommmentListHandler(serverCtx),
			},
		},
	)
}
