// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package mysqlmanageserverclient

import (
	mysqlmanageserver2 "awesomeProject/dou-yin/apps/commaction/rpc/mysqlmanage/types/mysqlmanageserver"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVideoFavoriteRequest              = mysqlmanageserver2.AddVideoFavoriteRequest
	AddVideoFavoriteResponse             = mysqlmanageserver2.AddVideoFavoriteResponse
	CheckIsFollowRequest                 = mysqlmanageserver2.CheckIsFollowRequest
	CheckIsFollowResponse                = mysqlmanageserver2.CheckIsFollowResponse
	CheckUserInfRequest                  = mysqlmanageserver2.CheckUserInfRequest
	CheckUserInfResponse                 = mysqlmanageserver2.CheckUserInfResponse
	CreatePublishActionViedeInfoRequest  = mysqlmanageserver2.CreatePublishActionViedeInfoRequest
	CreatePublishActionViedeInfoResponse = mysqlmanageserver2.CreatePublishActionViedeInfoResponse
	FavoriteVideoNumRequest              = mysqlmanageserver2.FavoriteVideoNumRequest
	FavoriteVideoNumResponse             = mysqlmanageserver2.FavoriteVideoNumResponse
	FeedUserInfo                         = mysqlmanageserver2.FeedUserInfo
	GetFavoriteVideoListRequest          = mysqlmanageserver2.GetFavoriteVideoListRequest
	GetFavoriteVideoListResponse         = mysqlmanageserver2.GetFavoriteVideoListResponse
	GetFeedUserInfoRequest               = mysqlmanageserver2.GetFeedUserInfoRequest
	GetFeedUserInfoResponse              = mysqlmanageserver2.GetFeedUserInfoResponse
	GetFeedVideoListRequest              = mysqlmanageserver2.GetFeedVideoListRequest
	GetFeedVideoListResponse             = mysqlmanageserver2.GetFeedVideoListResponse
	GetVideoListRequest                  = mysqlmanageserver2.GetVideoListRequest
	GetVideoListResponse                 = mysqlmanageserver2.GetVideoListResponse
	IsFavotiteRequest                    = mysqlmanageserver2.IsFavotiteRequest
	IsFavotiteResponse                   = mysqlmanageserver2.IsFavotiteResponse
	PublishActionVideoInfo               = mysqlmanageserver2.PublishActionVideoInfo
	RelationActionRequest                = mysqlmanageserver2.RelationActionRequest
	RelationActionResponse               = mysqlmanageserver2.RelationActionResponse
	RelationFollowListRequest            = mysqlmanageserver2.RelationFollowListRequest
	RelationFollowListResponse           = mysqlmanageserver2.RelationFollowListResponse
	RelationFollowerListRequest          = mysqlmanageserver2.RelationFollowerListRequest
	RelationFollowerListResponse         = mysqlmanageserver2.RelationFollowerListResponse
	RelationUser                         = mysqlmanageserver2.RelationUser
	SubVideoFavoriteRequest              = mysqlmanageserver2.SubVideoFavoriteRequest
	SubVideoFavoriteResponse             = mysqlmanageserver2.SubVideoFavoriteResponse
	UserInf                              = mysqlmanageserver2.UserInf
	UserLoginRequest                     = mysqlmanageserver2.UserLoginRequest
	UserLoginResponse                    = mysqlmanageserver2.UserLoginResponse
	UserRegisterRequest                  = mysqlmanageserver2.UserRegisterRequest
	UserRegisterResponse                 = mysqlmanageserver2.UserRegisterResponse
	Users                                = mysqlmanageserver2.Users
	VideoInfo                            = mysqlmanageserver2.VideoInfo
	VideoNumRequest                      = mysqlmanageserver2.VideoNumRequest
	VideoNumResponse                     = mysqlmanageserver2.VideoNumResponse

	MySQLManageServer interface {
		// 获得用户信息
		CheckUserInf(ctx context.Context, in *CheckUserInfRequest, opts ...grpc.CallOption) (*CheckUserInfResponse, error)
		// 发布列表视频信息
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		// 发布列表视频数量
		VideoNum(ctx context.Context, in *VideoNumRequest, opts ...grpc.CallOption) (*VideoNumResponse, error)
		// 关注、取消关注
		RelationAction(ctx context.Context, in *RelationActionRequest, opts ...grpc.CallOption) (*RelationActionResponse, error)
		// 粉丝列表
		RelationFollowerList(ctx context.Context, in *RelationFollowerListRequest, opts ...grpc.CallOption) (*RelationFollowerListResponse, error)
		// 关注列表
		RelationFollowList(ctx context.Context, in *RelationFollowListRequest, opts ...grpc.CallOption) (*RelationFollowListResponse, error)
		// 喜欢视频数量
		FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error)
		// 获取喜欢列表
		GetFavoriteVideoList(ctx context.Context, in *GetFavoriteVideoListRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListResponse, error)
		// 点赞
		AddVideoFavorite(ctx context.Context, in *AddVideoFavoriteRequest, opts ...grpc.CallOption) (*AddVideoFavoriteResponse, error)
		// 取消点赞
		SubVideoFavorite(ctx context.Context, in *SubVideoFavoriteRequest, opts ...grpc.CallOption) (*SubVideoFavoriteResponse, error)
	}

	defaultMySQLManageServer struct {
		cli zrpc.Client
	}
)

func NewMySQLManageServer(cli zrpc.Client) MySQLManageServer {
	return &defaultMySQLManageServer{
		cli: cli,
	}
}

// 获得用户信息
func (m *defaultMySQLManageServer) CheckUserInf(ctx context.Context, in *CheckUserInfRequest, opts ...grpc.CallOption) (*CheckUserInfResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.CheckUserInf(ctx, in, opts...)
}

// 发布列表视频信息
func (m *defaultMySQLManageServer) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

// 发布列表视频数量
func (m *defaultMySQLManageServer) VideoNum(ctx context.Context, in *VideoNumRequest, opts ...grpc.CallOption) (*VideoNumResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.VideoNum(ctx, in, opts...)
}

// 关注、取消关注
func (m *defaultMySQLManageServer) RelationAction(ctx context.Context, in *RelationActionRequest, opts ...grpc.CallOption) (*RelationActionResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationAction(ctx, in, opts...)
}

// 粉丝列表
func (m *defaultMySQLManageServer) RelationFollowerList(ctx context.Context, in *RelationFollowerListRequest, opts ...grpc.CallOption) (*RelationFollowerListResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationFollowerList(ctx, in, opts...)
}

// 关注列表
func (m *defaultMySQLManageServer) RelationFollowList(ctx context.Context, in *RelationFollowListRequest, opts ...grpc.CallOption) (*RelationFollowListResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationFollowList(ctx, in, opts...)
}

// 喜欢视频数量
func (m *defaultMySQLManageServer) FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.FavoriteVideoNum(ctx, in, opts...)
}

// 获取喜欢列表
func (m *defaultMySQLManageServer) GetFavoriteVideoList(ctx context.Context, in *GetFavoriteVideoListRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.GetFavoriteVideoList(ctx, in, opts...)
}

// 点赞
func (m *defaultMySQLManageServer) AddVideoFavorite(ctx context.Context, in *AddVideoFavoriteRequest, opts ...grpc.CallOption) (*AddVideoFavoriteResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.AddVideoFavorite(ctx, in, opts...)
}

// 取消点赞
func (m *defaultMySQLManageServer) SubVideoFavorite(ctx context.Context, in *SubVideoFavoriteRequest, opts ...grpc.CallOption) (*SubVideoFavoriteResponse, error) {
	client := mysqlmanageserver2.NewMySQLManageServerClient(m.cli.Conn())
	return client.SubVideoFavorite(ctx, in, opts...)
}
