// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"awesomeProject/dou-yin/apps/relationfollow/cmd/api/internal/handler/RelationFollowInterface"
	"awesomeProject/dou-yin/apps/relationfollow/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/relation/action",
				Handler: RelationFollowInterface.RelationActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follow/list",
				Handler: RelationFollowInterface.RelationFollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follower/list",
				Handler: RelationFollowInterface.RelationFollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/friend/list",
				Handler: RelationFollowInterface.RelationFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/message/chat",
				Handler: RelationFollowInterface.MessageChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/message/action",
				Handler: RelationFollowInterface.MessageActionHandler(serverCtx),
			},
		},
	)
}
