// Code generated by goctl. DO NOT EDIT.
package handler

import (
	video2 "awesomeProject/dou-yin/apps/video/cmd/api/internal/handler/video"
	"awesomeProject/dou-yin/apps/video/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UploadFile},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: video2.PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list/:userId",
					Handler: video2.PublishVideoListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/douyin/publish"),
	)
}
