// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package server

import (
	logic2 "awesomeProject/dou-yin/apps/commaction/rpc/mysqlmanage/internal/logic"
	"awesomeProject/dou-yin/apps/commaction/rpc/mysqlmanage/internal/svc"
	mysqlmanageserver2 "awesomeProject/dou-yin/apps/commaction/rpc/mysqlmanage/types/mysqlmanageserver"
	"context"
)

type MySQLManageServerServer struct {
	svcCtx *svc.ServiceContext
	mysqlmanageserver2.UnimplementedMySQLManageServerServer
}

func NewMySQLManageServerServer(svcCtx *svc.ServiceContext) *MySQLManageServerServer {
	return &MySQLManageServerServer{
		svcCtx: svcCtx,
	}
}

// 获得用户信息
func (s *MySQLManageServerServer) CheckUserInf(ctx context.Context, in *mysqlmanageserver2.CheckUserInfRequest) (*mysqlmanageserver2.CheckUserInfResponse, error) {
	l := logic2.NewCheckUserInfLogic(ctx, s.svcCtx)
	return l.CheckUserInf(in)
}

// 发布列表视频信息
func (s *MySQLManageServerServer) GetVideoList(ctx context.Context, in *mysqlmanageserver2.GetVideoListRequest) (*mysqlmanageserver2.GetVideoListResponse, error) {
	l := logic2.NewGetVideoListLogic(ctx, s.svcCtx)
	return l.GetVideoList(in)
}

// 发布列表视频数量
func (s *MySQLManageServerServer) VideoNum(ctx context.Context, in *mysqlmanageserver2.VideoNumRequest) (*mysqlmanageserver2.VideoNumResponse, error) {
	l := logic2.NewVideoNumLogic(ctx, s.svcCtx)
	return l.VideoNum(in)
}

// 关注、取消关注
func (s *MySQLManageServerServer) RelationAction(ctx context.Context, in *mysqlmanageserver2.RelationActionRequest) (*mysqlmanageserver2.RelationActionResponse, error) {
	l := logic2.NewRelationActionLogic(ctx, s.svcCtx)
	return l.RelationAction(in)
}

// 粉丝列表
func (s *MySQLManageServerServer) RelationFollowerList(ctx context.Context, in *mysqlmanageserver2.RelationFollowerListRequest) (*mysqlmanageserver2.RelationFollowerListResponse, error) {
	l := logic2.NewRelationFollowerListLogic(ctx, s.svcCtx)
	return l.RelationFollowerList(in)
}

// 关注列表
func (s *MySQLManageServerServer) RelationFollowList(ctx context.Context, in *mysqlmanageserver2.RelationFollowListRequest) (*mysqlmanageserver2.RelationFollowListResponse, error) {
	l := logic2.NewRelationFollowListLogic(ctx, s.svcCtx)
	return l.RelationFollowList(in)
}

// 喜欢视频数量
func (s *MySQLManageServerServer) FavoriteVideoNum(ctx context.Context, in *mysqlmanageserver2.FavoriteVideoNumRequest) (*mysqlmanageserver2.FavoriteVideoNumResponse, error) {
	l := logic2.NewFavoriteVideoNumLogic(ctx, s.svcCtx)
	return l.FavoriteVideoNum(in)
}

// 获取喜欢列表
func (s *MySQLManageServerServer) GetFavoriteVideoList(ctx context.Context, in *mysqlmanageserver2.GetFavoriteVideoListRequest) (*mysqlmanageserver2.GetFavoriteVideoListResponse, error) {
	l := logic2.NewGetFavoriteVideoListLogic(ctx, s.svcCtx)
	return l.GetFavoriteVideoList(in)
}

// 点赞
func (s *MySQLManageServerServer) AddVideoFavorite(ctx context.Context, in *mysqlmanageserver2.AddVideoFavoriteRequest) (*mysqlmanageserver2.AddVideoFavoriteResponse, error) {
	l := logic2.NewAddVideoFavoriteLogic(ctx, s.svcCtx)
	return l.AddVideoFavorite(in)
}

// 取消点赞
func (s *MySQLManageServerServer) SubVideoFavorite(ctx context.Context, in *mysqlmanageserver2.SubVideoFavoriteRequest) (*mysqlmanageserver2.SubVideoFavoriteResponse, error) {
	l := logic2.NewSubVideoFavoriteLogic(ctx, s.svcCtx)
	return l.SubVideoFavorite(in)
}
