// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Status_code int64  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type UserInfoResponse struct {
	Status_code    int64  `json:"status_code"`
	Status_msg     string `json:"status_msg"`
	Id             int64  `json:"id"`
	Name           string `json:"name"`
	Follow_count   int64  `json:"follow_count"`
	Follower_count int64  `json:"follower_count"`
	Is_follow      bool   `json:"is_follow"`
}
