// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoriteFieldNames          = builder.RawFieldNames(&Favorite{})
	favoriteRows                = strings.Join(favoriteFieldNames, ",")
	favoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(favoriteFieldNames, "`record_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(favoriteFieldNames, "`record_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDouyinFavoriteFavoriteRecordIdPrefix = "cache:douyinFavorite:favorite:recordId:"
)

type (
	favoriteModel interface {
		Insert(ctx context.Context, data *Favorite) (sql.Result, error)
		FindOne(ctx context.Context, recordId int64) (*Favorite, error)
		Update(ctx context.Context, data *Favorite) error
		Delete(ctx context.Context, recordId int64) error
	}

	defaultFavoriteModel struct {
		sqlc.CachedConn
		table string
	}

	Favorite struct {
		RecordId        int64         `db:"record_id"`         // 记录编号,自增
		FavoriteVideoId sql.NullInt64 `db:"favorite_video_id"` // 被点赞视频id
		FavoriteUserId  sql.NullInt64 `db:"favorite_user_id"`  // 点赞账号id
		RecordTime      sql.NullTime  `db:"record_time"`       // 记录时间
	}
)

func newFavoriteModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) Delete(ctx context.Context, recordId int64) error {
	douyinFavoriteFavoriteRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteRecordIdPrefix, recordId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `record_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, recordId)
	}, douyinFavoriteFavoriteRecordIdKey)
	return err
}

func (m *defaultFavoriteModel) FindOne(ctx context.Context, recordId int64) (*Favorite, error) {
	douyinFavoriteFavoriteRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteRecordIdPrefix, recordId)
	var resp Favorite
	err := m.QueryRowCtx(ctx, &resp, douyinFavoriteFavoriteRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `record_id` = ? limit 1", favoriteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, recordId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) Insert(ctx context.Context, data *Favorite) (sql.Result, error) {
	douyinFavoriteFavoriteRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteRecordIdPrefix, data.RecordId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, favoriteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FavoriteVideoId, data.FavoriteUserId, data.RecordTime)
	}, douyinFavoriteFavoriteRecordIdKey)
	return ret, err
}

func (m *defaultFavoriteModel) Update(ctx context.Context, data *Favorite) error {
	douyinFavoriteFavoriteRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteRecordIdPrefix, data.RecordId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `record_id` = ?", m.table, favoriteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FavoriteVideoId, data.FavoriteUserId, data.RecordTime, data.RecordId)
	}, douyinFavoriteFavoriteRecordIdKey)
	return err
}

func (m *defaultFavoriteModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteRecordIdPrefix, primary)
}

func (m *defaultFavoriteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `record_id` = ? limit 1", favoriteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoriteModel) tableName() string {
	return m.table
}
