// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followFieldNames          = builder.RawFieldNames(&Follow{})
	followRows                = strings.Join(followFieldNames, ",")
	followRowsExpectAutoSet   = strings.Join(stringx.Remove(followFieldNames, "`record_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followRowsWithPlaceHolder = strings.Join(stringx.Remove(followFieldNames, "`record_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDouyinFollowFollowRecordIdPrefix = "cache:douyinFollow:follow:recordId:"
)

type (
	followModel interface {
		Insert(ctx context.Context, data *Follow) (sql.Result, error)
		FindOne(ctx context.Context, recordId int64) (*Follow, error)
		Update(ctx context.Context, data *Follow) error
		Delete(ctx context.Context, recordId int64) error
	}

	defaultFollowModel struct {
		sqlc.CachedConn
		table string
	}

	Follow struct {
		RecordId   int64        `db:"record_id"`   // 记录编号，自增
		UserId     int64        `db:"user_id"`     // 被关注的账号id
		FollowerId int64        `db:"follower_id"` // 粉丝账号id
		RecordTime sql.NullTime `db:"record_time"` // 关注时间
	}
)

func newFollowModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFollowModel {
	return &defaultFollowModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`follow`",
	}
}

func (m *defaultFollowModel) Delete(ctx context.Context, recordId int64) error {
	douyinFollowFollowRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFollowFollowRecordIdPrefix, recordId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `record_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, recordId)
	}, douyinFollowFollowRecordIdKey)
	return err
}

func (m *defaultFollowModel) FindOne(ctx context.Context, recordId int64) (*Follow, error) {
	douyinFollowFollowRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFollowFollowRecordIdPrefix, recordId)
	var resp Follow
	err := m.QueryRowCtx(ctx, &resp, douyinFollowFollowRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `record_id` = ? limit 1", followRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, recordId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowModel) Insert(ctx context.Context, data *Follow) (sql.Result, error) {
	douyinFollowFollowRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFollowFollowRecordIdPrefix, data.RecordId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.RecordTime)
	}, douyinFollowFollowRecordIdKey)
	return ret, err
}

func (m *defaultFollowModel) Update(ctx context.Context, data *Follow) error {
	douyinFollowFollowRecordIdKey := fmt.Sprintf("%s%v", cacheDouyinFollowFollowRecordIdPrefix, data.RecordId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `record_id` = ?", m.table, followRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.RecordTime, data.RecordId)
	}, douyinFollowFollowRecordIdKey)
	return err
}

func (m *defaultFollowModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDouyinFollowFollowRecordIdPrefix, primary)
}

func (m *defaultFollowModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `record_id` = ? limit 1", followRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowModel) tableName() string {
	return m.table
}
