// Code generated by goctl. DO NOT EDIT.
// Source: mongodbmanage.proto

package server

import (
	"awesomeProject/dou-yin/apps/commaction/cmd/rpc/mongodbmanage/internal/logic"
	"awesomeProject/dou-yin/apps/commaction/cmd/rpc/mongodbmanage/internal/svc"
	"awesomeProject/dou-yin/apps/commaction/cmd/rpc/mongodbmanage/types/mongodbmanageserver"
	"context"
)

type MongodbManageServerServer struct {
	svcCtx *svc.ServiceContext
	mongodbmanageserver.UnimplementedMongodbManageServerServer
}

func NewMongodbManageServerServer(svcCtx *svc.ServiceContext) *MongodbManageServerServer {
	return &MongodbManageServerServer{
		svcCtx: svcCtx,
	}
}

func (s *MongodbManageServerServer) MakeComment(ctx context.Context, in *mongodbmanageserver.CommentActionRequest) (*mongodbmanageserver.CommentActionResponse, error) {
	l := logic.NewMakeCommentLogic(ctx, s.svcCtx)
	return l.MakeComment(in)
}

func (s *MongodbManageServerServer) GetComment(ctx context.Context, in *mongodbmanageserver.CommentListRequest) (*mongodbmanageserver.CommentListResponse, error) {
	l := logic.NewGetCommentLogic(ctx, s.svcCtx)
	return l.GetComment(in)
}

func (s *MongodbManageServerServer) GetMessage(ctx context.Context, in *mongodbmanageserver.MessageChatRequest) (*mongodbmanageserver.MessageChatResponse, error) {
	l := logic.NewGetMessageLogic(ctx, s.svcCtx)
	return l.GetMessage(in)
}

func (s *MongodbManageServerServer) SendMessage(ctx context.Context, in *mongodbmanageserver.MessageActionRequest) (*mongodbmanageserver.MessageActionResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}
