// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoriteFieldNames          = builder.RawFieldNames(&Favorite{})
	favoriteRows                = strings.Join(favoriteFieldNames, ",")
	favoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDouyinFavoriteFavoriteIdPrefix = "cache:douyinFavorite:favorite:id:"
)

type (
	favoriteModel interface {
		Insert(ctx context.Context, data *Favorite) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Favorite, error)
		FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Favorite, error)
		Update(ctx context.Context, data *Favorite) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFavoriteModel struct {
		sqlc.CachedConn
		table string
	}

	Favorite struct {
		Id         int64     `db:"id"`          // 自增主键
		UserId     int64     `db:"user_id"`     // 用户id
		VideoId    int64     `db:"video_id"`    // 视频id
		CreateTime time.Time `db:"create_time"` // 点赞时间
		Cancel     int64     `db:"cancel"`      // 默认点赞为1，取消赞为0
	}
)

func newFavoriteModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) Delete(ctx context.Context, id int64) error {
	douyinFavoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, douyinFavoriteFavoriteIdKey)
	return err
}

func (m *defaultFavoriteModel) FindOne(ctx context.Context, id int64) (*Favorite, error) {
	douyinFavoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteIdPrefix, id)
	var resp Favorite
	err := m.QueryRowCtx(ctx, &resp, douyinFavoriteFavoriteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*Favorite, error) {
	douyinLikesUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheDouyinFavoriteFavoriteIdPrefix, userId, videoId)
	var resp Favorite
	err := m.QueryRowIndexCtx(ctx, &resp, douyinLikesUserIdVideoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `video_id` = ? limit 1", favoriteRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, videoId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) Insert(ctx context.Context, data *Favorite) (sql.Result, error) {
	douyinFavoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, favoriteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.VideoId)
	}, douyinFavoriteFavoriteIdKey)
	return ret, err
}

func (m *defaultFavoriteModel) Update(ctx context.Context, data *Favorite) error {
	douyinFavoriteFavoriteIdKey := fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, favoriteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.VideoId, data.Id)
	}, douyinFavoriteFavoriteIdKey)
	return err
}

func (m *defaultFavoriteModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDouyinFavoriteFavoriteIdPrefix, primary)
}

func (m *defaultFavoriteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoriteModel) tableName() string {
	return m.table
}
