// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	like "awesomeProject/dou-yin/like/cmd/api/internal/handler/like"
	"awesomeProject/dou-yin/like/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: like.LikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: like.LikeListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/douyin/favourite"),
	)
}
