// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package mysqlmanageserverclient

import (
	"awesomeProject/dou-yin/apps/commaction/cmd/rpc/mysqlmanage/types/mysqlmanageserver"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVideoFavoriteRequest              = mysqlmanageserver.AddVideoFavoriteRequest
	AddVideoFavoriteResponse             = mysqlmanageserver.AddVideoFavoriteResponse
	CheckIsFollowRequest                 = mysqlmanageserver.CheckIsFollowRequest
	CheckIsFollowResponse                = mysqlmanageserver.CheckIsFollowResponse
	CheckUserInfRequest                  = mysqlmanageserver.CheckUserInfRequest
	CheckUserInfResponse                 = mysqlmanageserver.CheckUserInfResponse
	CreatePublishActionViedeInfoRequest  = mysqlmanageserver.CreatePublishActionViedeInfoRequest
	CreatePublishActionViedeInfoResponse = mysqlmanageserver.CreatePublishActionViedeInfoResponse
	FavoriteVideoNumRequest              = mysqlmanageserver.FavoriteVideoNumRequest
	FavoriteVideoNumResponse             = mysqlmanageserver.FavoriteVideoNumResponse
	FeedUserInfo                         = mysqlmanageserver.FeedUserInfo
	GetFavoriteVideoListRequest          = mysqlmanageserver.GetFavoriteVideoListRequest
	GetFavoriteVideoListResponse         = mysqlmanageserver.GetFavoriteVideoListResponse
	GetFeedUserInfoRequest               = mysqlmanageserver.GetFeedUserInfoRequest
	GetFeedUserInfoResponse              = mysqlmanageserver.GetFeedUserInfoResponse
	GetFeedVideoListRequest              = mysqlmanageserver.GetFeedVideoListRequest
	GetFeedVideoListResponse             = mysqlmanageserver.GetFeedVideoListResponse
	GetVideoListRequest                  = mysqlmanageserver.GetVideoListRequest
	GetVideoListResponse                 = mysqlmanageserver.GetVideoListResponse
	IsFavotiteRequest                    = mysqlmanageserver.IsFavotiteRequest
	IsFavotiteResponse                   = mysqlmanageserver.IsFavotiteResponse
	PublishActionVideoInfo               = mysqlmanageserver.PublishActionVideoInfo
	RelationActionRequest                = mysqlmanageserver.RelationActionRequest
	RelationActionResponse               = mysqlmanageserver.RelationActionResponse
	RelationFollowListRequest            = mysqlmanageserver.RelationFollowListRequest
	RelationFollowListResponse           = mysqlmanageserver.RelationFollowListResponse
	RelationFollowerListRequest          = mysqlmanageserver.RelationFollowerListRequest
	RelationFollowerListResponse         = mysqlmanageserver.RelationFollowerListResponse
	RelationUser                         = mysqlmanageserver.RelationUser
	SubVideoFavoriteRequest              = mysqlmanageserver.SubVideoFavoriteRequest
	SubVideoFavoriteResponse             = mysqlmanageserver.SubVideoFavoriteResponse
	UserInf                              = mysqlmanageserver.UserInf
	UserLoginRequest                     = mysqlmanageserver.UserLoginRequest
	UserLoginResponse                    = mysqlmanageserver.UserLoginResponse
	UserRegisterRequest                  = mysqlmanageserver.UserRegisterRequest
	UserRegisterResponse                 = mysqlmanageserver.UserRegisterResponse
	Users                                = mysqlmanageserver.Users
	VideoInfo                            = mysqlmanageserver.VideoInfo
	VideoNumRequest                      = mysqlmanageserver.VideoNumRequest
	VideoNumResponse                     = mysqlmanageserver.VideoNumResponse

	MySQLManageServer interface {
		// 获得用户信息
		CheckUserInf(ctx context.Context, in *CheckUserInfRequest, opts ...grpc.CallOption) (*CheckUserInfResponse, error)
		// 发布列表视频信息
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		// 发布列表视频数量
		VideoNum(ctx context.Context, in *VideoNumRequest, opts ...grpc.CallOption) (*VideoNumResponse, error)
		// 关注、取消关注
		RelationAction(ctx context.Context, in *RelationActionRequest, opts ...grpc.CallOption) (*RelationActionResponse, error)
		// 粉丝列表
		RelationFollowerList(ctx context.Context, in *RelationFollowerListRequest, opts ...grpc.CallOption) (*RelationFollowerListResponse, error)
		// 关注列表
		RelationFollowList(ctx context.Context, in *RelationFollowListRequest, opts ...grpc.CallOption) (*RelationFollowListResponse, error)
		// 喜欢视频数量
		FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error)
		// 获取喜欢列表
		GetFavoriteVideoList(ctx context.Context, in *GetFavoriteVideoListRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListResponse, error)
		// 点赞
		AddVideoFavorite(ctx context.Context, in *AddVideoFavoriteRequest, opts ...grpc.CallOption) (*AddVideoFavoriteResponse, error)
		// 取消点赞
		SubVideoFavorite(ctx context.Context, in *SubVideoFavoriteRequest, opts ...grpc.CallOption) (*SubVideoFavoriteResponse, error)
	}

	defaultMySQLManageServer struct {
		cli zrpc.Client
	}
)

func NewMySQLManageServer(cli zrpc.Client) MySQLManageServer {
	return &defaultMySQLManageServer{
		cli: cli,
	}
}

// 获得用户信息
func (m *defaultMySQLManageServer) CheckUserInf(ctx context.Context, in *CheckUserInfRequest, opts ...grpc.CallOption) (*CheckUserInfResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.CheckUserInf(ctx, in, opts...)
}

// 发布列表视频信息
func (m *defaultMySQLManageServer) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

// 发布列表视频数量
func (m *defaultMySQLManageServer) VideoNum(ctx context.Context, in *VideoNumRequest, opts ...grpc.CallOption) (*VideoNumResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.VideoNum(ctx, in, opts...)
}

// 关注、取消关注
func (m *defaultMySQLManageServer) RelationAction(ctx context.Context, in *RelationActionRequest, opts ...grpc.CallOption) (*RelationActionResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationAction(ctx, in, opts...)
}

// 粉丝列表
func (m *defaultMySQLManageServer) RelationFollowerList(ctx context.Context, in *RelationFollowerListRequest, opts ...grpc.CallOption) (*RelationFollowerListResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationFollowerList(ctx, in, opts...)
}

// 关注列表
func (m *defaultMySQLManageServer) RelationFollowList(ctx context.Context, in *RelationFollowListRequest, opts ...grpc.CallOption) (*RelationFollowListResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.RelationFollowList(ctx, in, opts...)
}

// 喜欢视频数量
func (m *defaultMySQLManageServer) FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.FavoriteVideoNum(ctx, in, opts...)
}

// 获取喜欢列表
func (m *defaultMySQLManageServer) GetFavoriteVideoList(ctx context.Context, in *GetFavoriteVideoListRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.GetFavoriteVideoList(ctx, in, opts...)
}

// 点赞
func (m *defaultMySQLManageServer) AddVideoFavorite(ctx context.Context, in *AddVideoFavoriteRequest, opts ...grpc.CallOption) (*AddVideoFavoriteResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.AddVideoFavorite(ctx, in, opts...)
}

// 取消点赞
func (m *defaultMySQLManageServer) SubVideoFavorite(ctx context.Context, in *SubVideoFavoriteRequest, opts ...grpc.CallOption) (*SubVideoFavoriteResponse, error) {
	client := mysqlmanageserver.NewMySQLManageServerClient(m.cli.Conn())
	return client.SubVideoFavorite(ctx, in, opts...)
}
