// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User_id uint64 `json:"user_id"`
	Token   string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	User_id uint64 `json:"user_id"`
	Token   string `json:"token"`
}

type UserInfoRequest struct {
	Id    uint64 `json:"id"`
	Token string `json:"token"`
}

type UserInfoResponse struct {
	Status_code    uint64 `json:"status_code"`
	Status_msg     string `json:"status_msg"`
	Id             string `json:"id"`
	Name           uint64 `json:"name"`
	Follow_count   uint64 `json:"follow_count"`
	Follower_count uint64 `json:"follower_count"`
	Is_follow      uint64 `json:"is_follow"`
}
